### ISSUE TITLE
Enable additional kernel installation

### ISSUE THREAD

**Issue by vpavlin** [thoth-station/s2i-minimal-notebook#12]
**Is your feature request related to a problem? Please describe.**
Some users noted they need to install/create additional kernels, so it might make sense to add some code to the `assemble` script to make is as simple as possible

**Describe the solution you'd like**
While playing around with this I came up with this "solution":

* add `kernels` directory
* each subdir of ^ represents additional kernel
* a user can provide file `metadata`, `install.sh` and `requirements.txt` (or `Pipfile` & `Pipfile.lock`)
* `assemble` will iterate over `kernels/` folder and run `install.sh` which sources `metadata` and runs `pip install` (or `pipenv install`)

E.g.:

metadata:
```
kernel_name=livy
kernel_display_name="Python 3 (livy)"
kernel_python_version="python3"
```

Example implementation in git: https://github.com/vpavlin/notebook/commit/ef0c962c1a8495bbf13adde4e7e771b0082bf4ec

I am also providing "default" `install.sh` which would be used if `install.sh` does not exist in `kernels/...` subdir to simplify further.

I tried to also use this for installation of non-python kernels - e.g. I turned https://github.com/vpavlin/julia-jupyter-notebooks/blob/master/.s2i/bin/assemble into an `install.sh` here: https://github.com/vpavlin/notebook/tree/master/minimal-notebook/kernels/julia

**Describe alternatives you've considered**
Leave it up to user completely, which brings some confusion since installing new kernels is not entirely straightforward in s2i environment.

Some documentation would probably help

WDYT @harshad16 @momoadc

![Screenshot from 2020-08-19 12-54-25](https://user-images.githubusercontent.com/4759808/90626590-76011c00-e21b-11ea-82c9-cb56c5924ba7.png)

**Comment by goern** [comment]
/unassign @harshad16 
/priority backlog

@pacospace could you please evaluate with Vasek if this feature is still required
