### ISSUE TITLE
pipfile and requirements.in are not in sync

### ISSUE THREAD

**Issue by pacospace** [thoth-station/s2i-minimal-notebook#23]

**Comment by fridex** [comment]
We should be able to detect this automatically: https://github.com/thoth-station/kebechet/tree/master/kebechet/managers/pipfile_requirements This kebechet manager probably needs revisiting.

**Comment by fridex** [comment]
And ideally have this handled by a pre-commit hook instead https://github.com/thoth-station/template-project/issues/13
