### ISSUE TITLE
IProgress not found. Please update jupyter and ipywidgets

### ISSUE THREAD

**Issue by goern** [thoth-station/s2i-minimal-notebook#33]
**Describe the bug**

@cfchase @TreeinRandomForest 
hey, for the benchmarking Sanjay came up with, we had an issue trying to get it to run his notebook on the Elyra build but it ran fine on other builds and services.  

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-4-6c92c34154f1> in <module>
      1 from torchvision.datasets import MNIST
----> 2 data = MNIST('./', download=True)

<Chris snip/>

/opt/app-root/lib/python3.6/site-packages/tqdm/notebook.py in status_printer(_, total, desc, ncols)
     95         if IProgress is None:  # #187 #451 #558 #872
     96             raise ImportError(
---> 97                 "IProgress not found. Please update jupyter and ipywidgets."
     98                 " See https://ipywidgets.readthedocs.io/en/stable"
     99                 "/user_install.html")

ImportError: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html


```

/kind bug
/assign @pacospace 
/sig build

**Comment by goern** [comment]
quay.io/thoth-station/s2i-lab-elyra@sha256:f1ff25c5c018b93890e7a6129d09c65611460493900253af7036f9646a3f79c9
is the image used

**Comment by harshad16** [comment]
@goern  are you suggesting in including the packages:
https://pypi.org/project/jupyter/
https://pypi.org/project/ipywidgets/

in the s2i-minimal-notebook as they are not available ?
seems like the issue happens in s2i-lab-elyra image , would you like to move it to https://github.com/opendatahub-io/s2i-lab-elyra

**Comment by pacospace** [comment]
> @goern are you suggesting in including the packages:
> https://pypi.org/project/jupyter/
> https://pypi.org/project/ipywidgets/
> 
> in the s2i-minimal-notebook as they are not available ?
> seems like the issue happens in s2i-lab-elyra image , would you like to move it to https://github.com/opendatahub-io/s2i-lab-elyra

in Elyra you don't use jupyter package indeed, nor ipywidgets, those are for classical notebooks, Elyra uses JupyterLab on the bacground and the packages used are different actually and in 3.0 release last month they got rid of many things.

From Elyra:

```
        'autopep8',
        'entrypoints>=0.3',
        'jinja2>=2.11,<3.0',
        'jsonschema>=3.2.0',
        'jupyter_core>=4.0,<5.0',
        'jupyter_client>=6.1.7',
        'jupyter_server>=1.2.0',
        'jupyterlab>=3.0.0',
        'jupyterlab-git==0.30.0b1',
        'jupyterlab-lsp>=3.0.0',
        'jupyter-resource-usage>=0.5.1',
        'kfp-notebook~=0.18.0',
        'kfp==1.1.2',
        'kfp-tekton==0.5.1rc1',
        'minio>=5.0.7,<7.0.0',
        'nbclient>=0.5.1',
        'nbconvert>=5.6.1,<6.0',
        'nbdime>=3.0.0.b1',
        'nbformat>=5.1.2',
        'papermill>=2.1.3',
        'python-language-server[all]>=0.36.2',
        'requests>=2.9.1,<3.0',
        'rfc3986-validator>=0.1.1',
        'traitlets>=4.3.2',
        'urllib3>=1.24.2',
        'websocket-client',
```

**Comment by harshad16** [comment]
> in Elyra you don't use jupyter package indeed, nor ipywidgets, those are for classical notebooks, Elyra uses JupyterLab on the bacground and the packages used are different actually and in 3.0 release last month they got rid of many things.
> 
> From Elyra:
> 
> ```
>         'autopep8',
>         'entrypoints>=0.3',
>         'jinja2>=2.11,<3.0',
>         'jsonschema>=3.2.0',
>         'jupyter_core>=4.0,<5.0',
>         'jupyter_client>=6.1.7',
>         'jupyter_server>=1.2.0',
>         'jupyterlab>=3.0.0',
>         'jupyterlab-git==0.30.0b1',
>         'jupyterlab-lsp>=3.0.0',
>         'jupyter-resource-usage>=0.5.1',
>         'kfp-notebook~=0.18.0',
>         'kfp==1.1.2',
>         'kfp-tekton==0.5.1rc1',
>         'minio>=5.0.7,<7.0.0',
>         'nbclient>=0.5.1',
>         'nbconvert>=5.6.1,<6.0',
>         'nbdime>=3.0.0.b1',
>         'nbformat>=5.1.2',
>         'papermill>=2.1.3',
>         'python-language-server[all]>=0.36.2',
>         'requests>=2.9.1,<3.0',
>         'rfc3986-validator>=0.1.1',
>         'traitlets>=4.3.2',
>         'urllib3>=1.24.2',
>         'websocket-client',
> ```
> 
> From Jupyterlab >3
> 
> ```
>     'ipython',
>     'packaging',
>     'tornado>=6.1.0',
>     'jupyter_core',
>     'jupyterlab_server~=2.0',
>     'jupyter_server~=1.2',
>     'nbclassic~=0.2',
>     'jinja2>=2.10'
> ```

what is this issue in regards to, @goern  can you please give more details? 
@pacospace can you share more on what is needed of the s2i-minimal based on this issue.

**Comment by cfchase** [comment]
> @goern are you suggesting in including the packages:
> https://pypi.org/project/jupyter/
> https://pypi.org/project/ipywidgets/
> 
> in the s2i-minimal-notebook as they are not available ?
> seems like the issue happens in s2i-lab-elyra image , would you like to move it to https://github.com/opendatahub-io/s2i-lab-elyra

Just FYI, s2i-minimal worked, however, the elyra image did not.  In my notebook I just had:

[1]
```
import sys
!{sys.executable} -m pip install torch
!{sys.executable} -m pip install torchvision
```

[2]
```
from torchvision.datasets import MNIST
data = MNIST('./', download=True)
```

I ended up with the ipywidgets error.

**Comment by pacospace** [comment]
is this still relevant?
