### ISSUE TITLE
Use latest pipenv in s2i-minimal notebook

### ISSUE THREAD

**Issue by pacospace** [thoth-station/s2i-minimal-notebook#38]
**Is your feature request related to a problem? Please describe.**
Image built on top of s2i minimal notebook have old pipenv.

**Describe the solution you'd like**
Update pipenv to latest.

**Describe alternatives you've considered**

**Additional context**
Ref: https://github.com/thoth-station/s2i-minimal-notebook/blob/ba0fefe0bf838924eac4ccfb439841c4289c05e2/.s2i/bin/assemble#L24

**Comment by harshad16** [comment]
https://github.com/thoth-station/s2i-minimal-notebook/blob/21884e3f472ff6f632e4c4c3eddd43b28bc8a9c9/.s2i/bin/assemble#L24
This is available in the version above v0.0.9
closing the issue, thanks for the issue.
