### ISSUE TITLE
Add branch support for JUPYTER_PRELOAD_REPOS

### ISSUE THREAD

**Issue by vpavlin** [thoth-station/s2i-minimal-notebook#4]
@lavlas recently added a feature to support specifying a branch for JUPYTER_PRELOAD_REPOS (see https://github.com/vpavlin/jupyter-notebooks/commit/7533977944e463b1834b98c936710afacc296d19)

**Comment by harshad16** [comment]
will open a support branch based on JUPYTER_PRELOAD_REPOS

**Comment by harshad16** [comment]
for now created a branch out of master and added the cherry-picked the commit of jupyter-preload-repos.
https://github.com/thoth-station/s2i-minimal-notebook/tree/jupyter-preload-repos

**Comment by vpavlin** [comment]
@LavLas If you have a chance, can you re-add your changes regarding checking out a branch to https://github.com/thoth-station/s2i-minimal-notebook/blob/master/builder/run#L35 ? Just noticed we lost this feature when we switched to thoth image..

**Comment by harshad16** [comment]
we have added them to a branch ,
https://github.com/thoth-station/s2i-minimal-notebook/commit/75934915e69f7cf47cac50e6471b99ff58df35e9
does it need more changes ?

**Comment by LaVLaS** [comment]
That was the only change that was required for the notebook to pull when `@BRANCH` was present in a repo url for `JUPYTER_PRELOAD_REPOS`

**Comment by vpavlin** [comment]
@harshad16 Your branch added the code in `start-notebook.sh`, but there is already the code without branch support in `run`...we need it only in one place and then merged to master:)

**Comment by harshad16** [comment]
ah, i see.
thanks for the pointer.
