### ISSUE TITLE
Do we need all the oc binaries?

### ISSUE THREAD

**Issue by vpavlin** [thoth-station/s2i-minimal-notebook#5]
I've noticed there is multiple oc binaries downloaded during the build - is it necessary?

https://github.com/thoth-station/s2i-minimal-notebook/blob/master/.s2i/bin/assemble#L59

**Comment by harshad16** [comment]
personally not sure if we need all of these oc version, however, it was taken from pull of the upstream https://github.com/jupyter-on-openshift/jupyter-notebooks/blob/develop/minimal-notebook/.s2i/bin/assemble. 

we can get rid of some and keep only once we require based upon the clusters we would be running jupyterhub in.
probably just keeping 3.11 and 4.3 feels good to me.

WDYT @vpavlin and @goern ?

**Comment by vpavlin** [comment]
Yeah, I think those two would make sense. 

It would be also good to simplify this https://github.com/thoth-station/s2i-minimal-notebook/blob/master/oc-wrapper.sh

and just match 3.* and 4.*
