### ISSUE TITLE
Include nbgitpuller into the notebook images.

### ISSUE THREAD

**Issue by harshad16** [thoth-station/s2i-minimal-notebook#536]
**Is your feature request related to a problem? Please describe.**

Hey! With the imminent launch of the "RHODS for education" initiative (basically using RHODS for courses, like we do with Boston University), it would be super cool to have nbgitpuller (https://github.com/jupyterhub/nbgitpuller) directly inside our base Jupyter image. This is really practical for those kind of use cases, as you can just have your students use a link to open a notebook in the environment with the git repo in the link automatically cloned at launch. It's different from our current feature where you can have a git repo cloned as part of a profile, because then it's only one repo per config. With nbgitpuller it's whatever repo you put in the link, so infinite options.
Having this baked in the base image (either s2i-minimal or generic-datascience) would allow to have it as a base feature, instead of having to put it in custom notebooks.

More details: https://chat.google.com/room/AAAAVjnVXFk/OemBSl4CVyg

**Comment by goern** [comment]
/kind feature
/priority critical-urgent

@harshad16 can we get this into the next milestone? wdyt?

**Comment by VannTen** [comment]
Hum, that kinda looks like (a specialized case of) CNBi, or am I misunderstanding ?

**Comment by harshad16** [comment]
> Hum, that kinda looks like (a specialized case of) CNBi, or am I misunderstanding ?

No this not specific to cnbi.
the nbgitpuller allow users to share there sourcecode.

**Comment by harshad16** [comment]
This is covered via https://github.com/thoth-station/s2i-minimal-notebook/pull/547
closing this.
