### ISSUE TITLE
[2pt] Gather information on the different methods to test the images.

### ISSUE THREAD

**Issue by harshad16** [thoth-station/s2i-minimal-notebook#541]
Acceptance criteria:
- [x] Get the info on the existing check (if any)done by aicoe-aiops, sig-data-science.
- [x] check if the import checks are enough on the list of the notebook repo.
- [x] Go through the notebook repo, estimate which package should be essential for unit test.

Additional: 
- [ ] based on the experience, consider the scenarios when package version update has impact on the standard functions

**Comment by harshad16** [comment]
cc: @Shreyanand

**Comment by Shreyanand** [comment]
Existing methods to test the images include 

1.`aicoe-ci/build-check` that tests the image once a PR is opened.
2. Developers also manually test the image on a local environment using s2i build and docker run as specified in the [documentation](https://github.com/AICoE/s2i-custom-notebook#how-to-build-the-image).

**Comment by Shreyanand** [comment]
Evaluated pipfiles here in this list:
```  "https://raw.githubusercontent.com/thoth-station/s2i-minimal-notebook/master/overlays/f35-python310/Pipfile",
    "https://raw.githubusercontent.com/thoth-station/s2i-minimal-notebook/master/overlays/f34-python39/Pipfile",
    "https://raw.githubusercontent.com/thoth-station/s2i-minimal-notebook/master/overlays/python38/Pipfile",
    "https://raw.githubusercontent.com/thoth-station/s2i-minimal-notebook/master/overlays/python36/Pipfile",
    "https://raw.githubusercontent.com/thoth-station/s2i-pytorch-notebook/master/Pipfile",
    "https://raw.githubusercontent.com/thoth-station/s2i-tensorflow-gpu-notebook/master/Pipfile",
    "https://raw.githubusercontent.com/thoth-station/s2i-generic-data-science-notebook/master/Pipfile",
    "https://raw.githubusercontent.com/thoth-station/s2i-tensorflow-gpu-notebook/master/Pipfile"
```
The set of packages used in this list  of pipfiles are:
```
{'beautifulsoup4',
 'bokeh',
 'boto3',
 'cloudpickle',
 'cython',
 'dask',
 'dill',
 'distributed',
 'elyra-python-editor-extension',
 'h5py',
 'ipython',
 'ipywidgets',
 'jupyter-bokeh',
 'jupyter-nbrequirements',
 'jupyter-tensorboard',
 'jupyter_kernel_gateway',
 'jupyterhub',
 'jupyterlab',
 'jupyterlab-git',
 'jupyterlab-requirements',
 'jupyterlab-s3-browser',
 'jupyterlab-spellchecker',
 'jupyterlab-tabnine',
 'kafka-python',
 'matplotlib',
 'notebook',
 'numpy',
 'pandas',
 'plotly',
 'pre-commit',
 'pyarrow',
 's3fs',
 'scikit-image',
 'scikit-learn',
 'scipy',
 'seaborn',
 'sqlalchemy',
 'statsmodels',
 'supervisor',
 'tensorboard',
 'tensorflow-gpu',
 'torch',
 'torchvision'}
 ```
From the looks of it, Import checks should be enough for all of them.

**Comment by Shreyanand** [comment]
Specific packages that should be unit tested imo:

's2i-generic-data-science-notebook_master': ['boto3',
  'matplotlib',
  'numpy',
  'pandas',
  'scikit-learn']

's2i-pytorch-notebook_master': [
  'matplotlib',
  'pandas',
  'plotly',
  'scikit-learn',
  'scipy',
  'tensorboard',
  'torch',
  'torchvision']

's2i-tensorflow-gpu-notebook_master': [
  'matplotlib',
  'pandas',
  'scikit-learn',
  'scipy',
  'tensorflow-gpu']

**Comment by harshad16** [comment]
Based on the experiment, it seems the import check could useful.
the complexity of the task was comparatively easier, reducing the story point to 2pt.

Thanks for the work.
