### ISSUE TITLE
add modules to minimal notebook

### ISSUE THREAD

**Issue by goern** [thoth-station/s2i-minimal-notebook#549]
**Is your feature request related to a problem? Please describe.**
We would like to extend the base/minimal notebook to contain
- git extension
- python editor
- python debugger

**Describe the solution you'd like**
Add dependencies to minimal-notebook, rebuild all dependent images, deliver to ODH@op1st

**Describe alternatives you've considered**
n/a

**Additional context**
This is based on some RHODS requirements

**Comment by harshad16** [comment]
- git extension already exists:
 https://github.com/thoth-station/s2i-minimal-notebook/blob/ee458d962652897ce004df5fe2a48dd632b26eb5/overlays/python38/Pipfile#L17
 - python editor from elyra are added in the next layer and not on minimal 
 
 can share the jira link or any document where these requirements were described

**Comment by mayaCostantini** [comment]
Following the discussion available at https://chat.google.com/room/AAAAVjnVXFk/lkcUaVc6uX0:

 **Should minimal images include tooling necessary for Elyra?**
- This minimal image will be used in different contexts that do not necessarily need Elyra
- The switch from JupyterHub to notebook-controller could impact the images
- Elyra extensions are already available in other notebook images

- [ ] Look into having `jupyter-server-proxy` into the minimal image to access web services used in a notebook externally (cc @harshad16 )

See the thread link above for discussion about optimizing image layers.

**Comment by harshad16** [comment]
The jupyter-server-proxy is already installed here: https://github.com/thoth-station/s2i-minimal-notebook/pull/560
closing this issue.
