### ISSUE TITLE
Introduce jupyterlab-tabnine

### ISSUE THREAD

**Issue by pacospace** [thoth-station/s2i-minimal-notebook#85]
**Is your feature request related to a problem? Please describe.**
Introduce jupyterlab-tabnine

**Describe the solution you'd like**
Introduce jupyterlab-tabnine

**Describe alternatives you've considered**

**Additional context**
https://github.com/codota/tabnine-jupyterlab

Upstream finally released, no more required: https://github.com/thoth-station/notebooks/issues/76

cc @durandom

**Comment by codificat** [comment]
It is compatible with jupyter so it *should* be just about installing it.

Maybe interesting for the Data Science SIG.

/remove-triage needs-information
/priority backlog
